remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

title: "Joshua C. Macdonald"
description: "Trait-functional modeling, structured population dynamics, and spectral theory"
minimal_mistakes_skin: "default"

# Enable custom pages folder
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Top nav
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Software"
    url: /software/
  - title: "CV"
    url: /cv/
  - title: "About"
    url: /about/


