# Site settings
title: "Joshua C. Macdonald"
description: "Trait-functional modeling, structured population dynamics, and spectral theory"
baseurl: "/macdonald-website" # the subpath of your site, e.g., /macdonald-website
url: "https://macdonaldjoshuacaleb.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Software"
    url: /software/
  - title: "CV"
    url: /cv/
  - title: "About"
    url: /about/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single


