# Site settings
title: "Joshua C. Macdonald"
description: "Trait-functional modeling, structured population dynamics, and spectral theory"
baseurl: "/macdonald-website" # subpath of the site
url: "https://macdonaldjoshuacaleb.github.io" # base site URL

# Theme
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Page output configuration
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults for page layout
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      nav: false
      author_profile: false
      related: false


# Navigation menu items (titles + links)
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Software"
    url: /software/
  - title: "CV"
    url: /cv/
  - title: "About"
    url: /about/

# Pages to include in the header nav bar
header_pages:
  - index.md
  - _pages/research.md
  - _pages/software.md
  - _pages/cv.md
  - _pages/about.md

