remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

title: "Joshua C. Macdonald"
description: "Trait-based spectral theory and structured population modeling"
minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

collections:
  pages:
    output: true
    permalink: /:path/

navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Software"
    url: /software/
  - title: "CV"
    url: /cv/
  - title: "About"
    url: /about/
